output_dir: "../content/수집 공고"
sort: "recent"   # recent(최신순) / relation(관련도순)
limit: 10        # 키워드당 최대 수집 건수

searches:
  - keyword: "NLP"
    career_types: ["신입", "경력없음"]
    locations: ["서울", "경기도"]

  - keyword: "자연어처리"
    career_types: ["신입", "경력없음"]
    locations: ["서울", "경기도"]
